import React from "react"
import { Inter } from 'next/font/google'

import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Next13 Demo App',
  description: 'Generated by create next app',
}

function Header() {
  return (
    <div className={'flex flex-row justify-center'}>
      Header here
    </div>
  )
}

function Footer() {
  return (
    <div className='flex flex-col items-center'>
      Footer here
    </div>
  )
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-full w-full`}>
        <Header/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
